/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData buttonCloseSlide =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData accountBox = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData buttonToolsAktif =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData iconRupiah = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData buttonLaporanAktif =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData iconDollar = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData iconEuro = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData buttonHomeAktif =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData buttonInputMasuk =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData buttonTransaksiAktif =
      IconData(0xe809, fontFamily: _kFontFam);
  static const IconData buttonTransaksiTidakAktif =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData buttonNotifikasi =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData buttonRefresh = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData iconDollarSingapore =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData buttonToolsTidakAktif =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData buttonLaporanTidakAktif =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData buttonInputKurs =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData buttonOpenSlide =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData buttonHomeTidakAktif =
      IconData(0xe812, fontFamily: _kFontFam);
  static const IconData buttonInputMutasi =
      IconData(0xe813, fontFamily: _kFontFam);
  static const IconData buttonInputKeluar =
      IconData(0xe814, fontFamily: _kFontFam);
  static const IconData buttonInputPindah =
      IconData(0xe815, fontFamily: _kFontFam);
}
